% cartpole_QP_solver - a fast interior point code generated by FORCES
%
%   OUTPUT = cartpole_QP_solver(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.f1 - column vector of length 15
%       PARAMS.lb1 - column vector of length 6
%       PARAMS.ub1 - column vector of length 6
%       PARAMS.A1 - matrix of size [20 x 15]
%       PARAMS.b1 - column vector of length 20
%       PARAMS.f2 - column vector of length 15
%       PARAMS.lb2 - column vector of length 1
%       PARAMS.ub2 - column vector of length 1
%       PARAMS.A2 - matrix of size [20 x 15]
%       PARAMS.b2 - column vector of length 20
%       PARAMS.f3 - column vector of length 15
%       PARAMS.lb3 - column vector of length 1
%       PARAMS.ub3 - column vector of length 1
%       PARAMS.A3 - matrix of size [20 x 15]
%       PARAMS.b3 - column vector of length 20
%       PARAMS.f4 - column vector of length 15
%       PARAMS.lb4 - column vector of length 1
%       PARAMS.ub4 - column vector of length 1
%       PARAMS.A4 - matrix of size [20 x 15]
%       PARAMS.b4 - column vector of length 20
%       PARAMS.f5 - column vector of length 15
%       PARAMS.lb5 - column vector of length 1
%       PARAMS.ub5 - column vector of length 1
%       PARAMS.A5 - matrix of size [20 x 15]
%       PARAMS.b5 - column vector of length 20
%       PARAMS.f6 - column vector of length 15
%       PARAMS.lb6 - column vector of length 1
%       PARAMS.ub6 - column vector of length 1
%       PARAMS.A6 - matrix of size [20 x 15]
%       PARAMS.b6 - column vector of length 20
%       PARAMS.f7 - column vector of length 15
%       PARAMS.lb7 - column vector of length 1
%       PARAMS.ub7 - column vector of length 1
%       PARAMS.A7 - matrix of size [20 x 15]
%       PARAMS.b7 - column vector of length 20
%       PARAMS.f8 - column vector of length 15
%       PARAMS.lb8 - column vector of length 1
%       PARAMS.ub8 - column vector of length 1
%       PARAMS.A8 - matrix of size [20 x 15]
%       PARAMS.b8 - column vector of length 20
%       PARAMS.f9 - column vector of length 15
%       PARAMS.lb9 - column vector of length 1
%       PARAMS.ub9 - column vector of length 1
%       PARAMS.A9 - matrix of size [20 x 15]
%       PARAMS.b9 - column vector of length 20
%       PARAMS.f10 - column vector of length 15
%       PARAMS.lb10 - column vector of length 1
%       PARAMS.ub10 - column vector of length 1
%       PARAMS.A10 - matrix of size [20 x 15]
%       PARAMS.b10 - column vector of length 20
%       PARAMS.f11 - column vector of length 15
%       PARAMS.lb11 - column vector of length 1
%       PARAMS.ub11 - column vector of length 1
%       PARAMS.A11 - matrix of size [20 x 15]
%       PARAMS.b11 - column vector of length 20
%       PARAMS.f12 - column vector of length 15
%       PARAMS.lb12 - column vector of length 1
%       PARAMS.ub12 - column vector of length 1
%       PARAMS.A12 - matrix of size [20 x 15]
%       PARAMS.b12 - column vector of length 20
%       PARAMS.f13 - column vector of length 15
%       PARAMS.lb13 - column vector of length 1
%       PARAMS.ub13 - column vector of length 1
%       PARAMS.A13 - matrix of size [20 x 15]
%       PARAMS.b13 - column vector of length 20
%       PARAMS.f14 - column vector of length 15
%       PARAMS.lb14 - column vector of length 1
%       PARAMS.ub14 - column vector of length 1
%       PARAMS.A14 - matrix of size [20 x 15]
%       PARAMS.b14 - column vector of length 20
%       PARAMS.f15 - column vector of length 15
%       PARAMS.lb15 - column vector of length 1
%       PARAMS.ub15 - column vector of length 1
%       PARAMS.A15 - matrix of size [20 x 15]
%       PARAMS.b15 - column vector of length 20
%       PARAMS.f16 - column vector of length 15
%       PARAMS.lb16 - column vector of length 1
%       PARAMS.ub16 - column vector of length 1
%       PARAMS.A16 - matrix of size [20 x 15]
%       PARAMS.b16 - column vector of length 20
%       PARAMS.f17 - column vector of length 15
%       PARAMS.lb17 - column vector of length 1
%       PARAMS.ub17 - column vector of length 1
%       PARAMS.A17 - matrix of size [20 x 15]
%       PARAMS.b17 - column vector of length 20
%       PARAMS.f18 - column vector of length 15
%       PARAMS.lb18 - column vector of length 1
%       PARAMS.ub18 - column vector of length 1
%       PARAMS.A18 - matrix of size [20 x 15]
%       PARAMS.b18 - column vector of length 20
%       PARAMS.f19 - column vector of length 14
%       PARAMS.lb19 - column vector of length 1
%       PARAMS.ub19 - column vector of length 1
%       PARAMS.A19 - matrix of size [20 x 14]
%       PARAMS.b19 - column vector of length 20
%       PARAMS.f20 - column vector of length 4
%       PARAMS.lb20 - column vector of length 4
%       PARAMS.ub20 - column vector of length 4
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.z1 - column vector of size 6
%       OUTPUT.z2 - column vector of size 6
%       OUTPUT.z3 - column vector of size 6
%       OUTPUT.z4 - column vector of size 6
%       OUTPUT.z5 - column vector of size 6
%       OUTPUT.z6 - column vector of size 6
%       OUTPUT.z7 - column vector of size 6
%       OUTPUT.z8 - column vector of size 6
%       OUTPUT.z9 - column vector of size 6
%       OUTPUT.z10 - column vector of size 6
%       OUTPUT.z11 - column vector of size 6
%       OUTPUT.z12 - column vector of size 6
%       OUTPUT.z13 - column vector of size 6
%       OUTPUT.z14 - column vector of size 6
%       OUTPUT.z15 - column vector of size 6
%       OUTPUT.z16 - column vector of size 6
%       OUTPUT.z17 - column vector of size 6
%       OUTPUT.z18 - column vector of size 6
%       OUTPUT.z19 - column vector of size 6
%       OUTPUT.z20 - column vector of size 4
%
%   [OUTPUT, EXITFLAG] = cartpole_QP_solver(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - Optimal solution has been found (subject to desired accuracy)
%       0 - Maximum number of interior point iterations reached
%      -7 - Line search could not progress
%
%   [OUTPUT, EXITFLAG, INFO] = cartpole_QP_solver(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also LICENSE
